inventory/config/routes.rb
Rails.application.routes.draw do
  resources :raw_materials
  resources :suppliers
  devise_for :users
  get 'dashboard/index'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Devise gem
  # 2. Ensure you have defined root_url to *something* in your config/routes.rb.
  # Defines the root path route ("/")
  # root "articles#index"
  root "dashboard#index"

end

inventory/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

inventory/app/models/raw_material.rb
class RawMaterial < ApplicationRecord
  belongs_to :supplier
end

inventory/app/models/supplier.rb
class Supplier < ApplicationRecord
end

inventory/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

inventory/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

inventory/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

inventory/app/controllers/raw_materials_controller.rb
class RawMaterialsController < ApplicationController
  before_action :set_raw_material, only: %i[ show edit update destroy ]

  # GET /raw_materials or /raw_materials.json
  def index
    @raw_materials = RawMaterial.all
  end

  # GET /raw_materials/1 or /raw_materials/1.json
  def show
  end

  # GET /raw_materials/new
  def new
    @raw_material = RawMaterial.new
  end

  # GET /raw_materials/1/edit
  def edit
  end

  # POST /raw_materials or /raw_materials.json
  def create
    @raw_material = RawMaterial.new(raw_material_params)

    respond_to do |format|
      if @raw_material.save
        format.html { redirect_to raw_material_url(@raw_material), notice: "Raw material was successfully created." }
        format.json { render :show, status: :created, location: @raw_material }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @raw_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /raw_materials/1 or /raw_materials/1.json
  def update
    respond_to do |format|
      if @raw_material.update(raw_material_params)
        format.html { redirect_to raw_material_url(@raw_material), notice: "Raw material was successfully updated." }
        format.json { render :show, status: :ok, location: @raw_material }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @raw_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /raw_materials/1 or /raw_materials/1.json
  def destroy
    @raw_material.destroy

    respond_to do |format|
      format.html { redirect_to raw_materials_url, notice: "Raw material was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raw_material
      @raw_material = RawMaterial.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def raw_material_params
      params.require(:raw_material).permit(:supplier_id, :name, :expires_on, :unit, :remarks)
    end
end

inventory/app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[ show edit update destroy ]

  # GET /suppliers or /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1 or /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers or /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to supplier_url(@supplier), notice: "Supplier was successfully created." }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1 or /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to supplier_url(@supplier), notice: "Supplier was successfully updated." }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1 or /suppliers/1.json
  def destroy
    @supplier.destroy

    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: "Supplier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supplier_params
      params.require(:supplier).permit(:name, :contact, :remarks)
    end
end

inventory/app/helpers/application_helper.rb
module ApplicationHelper
end

inventory/app/helpers/dashboard_helper.rb
module DashboardHelper
end

inventory/app/helpers/raw_materials_helper.rb
module RawMaterialsHelper
end

inventory/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

inventory/app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>
<nav>

<ul>
    <li>
<%= link_to "Home", root_url %>
    </li>
    <li>
<%= link_to "Suppliers", suppliers_url %>
    </li>
    <li>
<%= link_to "Raw Material", raw_materials_url %>
    </li>
</ul>
</nav>

inventory/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <header>
  <%= button_to("Log Out", destroy_user_session_path, method: :delete) if current_user %>
  </header>
    <%= yield %>
  </body>
</html>

inventory/app/views/raw_materials/_form.html.erb
<%= form_with(model: raw_material) do |form| %>
  <% if raw_material.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(raw_material.errors.count, "error") %> prohibited this raw_material from being saved:</h2>

      <ul>
        <% raw_material.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :supplier_id, style: "display: block" %>
    <%= form.text_field :supplier_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :expires_on, style: "display: block" %>
    <%= form.date_field :expires_on %>
  </div>

  <div>
    <%= form.label :unit, style: "display: block" %>
    <%= form.text_field :unit %>
  </div>

  <div>
    <%= form.label :remarks, style: "display: block" %>
    <%= form.text_field :remarks %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

inventory/app/views/raw_materials/_raw_material.html.erb
<div id="<%= dom_id raw_material %>">
  <p>
    <strong>Supplier:</strong>
    <%= raw_material.supplier_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= raw_material.name %>
  </p>

  <p>
    <strong>Expires on:</strong>
    <%= raw_material.expires_on %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= raw_material.unit %>
  </p>

  <p>
    <strong>Remarks:</strong>
    <%= raw_material.remarks %>
  </p>

</div>

inventory/app/views/raw_materials/edit.html.erb
<h1>Editing raw material</h1>

<%= render "form", raw_material: @raw_material %>

<br>

<div>
  <%= link_to "Show this raw material", @raw_material %> |
  <%= link_to "Back to raw materials", raw_materials_path %>
</div>

inventory/app/views/raw_materials/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Raw materials</h1>

<div id="raw_materials">
  <% @raw_materials.each do |raw_material| %>
    <%= render raw_material %>
    <p>
      <%= link_to "Show this raw material", raw_material %>
    </p>
  <% end %>
</div>

<%= link_to "New raw material", new_raw_material_path %>

inventory/app/views/raw_materials/new.html.erb
<h1>New raw material</h1>

<%= render "form", raw_material: @raw_material %>

<br>

<div>
  <%= link_to "Back to raw materials", raw_materials_path %>
</div>

inventory/app/views/raw_materials/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @raw_material %>

<div>
  <%= link_to "Edit this raw material", edit_raw_material_path(@raw_material) %> |
  <%= link_to "Back to raw materials", raw_materials_path %>

  <%= button_to "Destroy this raw material", @raw_material, method: :delete %>
</div>

inventory/app/views/suppliers/_form.html.erb
<%= form_with(model: supplier) do |form| %>
  <% if supplier.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
        <% supplier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :contact, style: "display: block" %>
    <%= form.text_field :contact %>
  </div>

  <div>
    <%= form.label :remarks, style: "display: block" %>
    <%= form.text_field :remarks %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

inventory/app/views/suppliers/_supplier.html.erb
<div id="<%= dom_id supplier %>">
  <p>
    <strong>Name:</strong>
    <%= supplier.name %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= supplier.contact %>
  </p>

  <p>
    <strong>Remarks:</strong>
    <%= supplier.remarks %>
  </p>

</div>

inventory/app/views/suppliers/edit.html.erb
<h1>Editing supplier</h1>

<%= render "form", supplier: @supplier %>

<br>

<div>
  <%= link_to "Show this supplier", @supplier %> |
  <%= link_to "Back to suppliers", suppliers_path %>
</div>

inventory/app/views/suppliers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Suppliers</h1>

<div id="suppliers">
  <% @suppliers.each do |supplier| %>
    <%= render supplier %>
    <p>
      <%= link_to "Show this supplier", supplier %>
    </p>
  <% end %>
</div>

<%= link_to "New supplier", new_supplier_path %>

inventory/app/views/suppliers/new.html.erb
<h1>New supplier</h1>

<%= render "form", supplier: @supplier %>

<br>

<div>
  <%= link_to "Back to suppliers", suppliers_path %>
</div>

inventory/app/views/suppliers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @supplier %>

<div>
  <%= link_to "Edit this supplier", edit_supplier_path(@supplier) %> |
  <%= link_to "Back to suppliers", suppliers_path %>

  <%= button_to "Destroy this supplier", @supplier, method: :delete %>
</div>